services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: spacey
      POSTGRES_PASSWORD: spacey
      POSTGRES_DB: spacey
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./server
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql+asyncpg://spacey:spacey@db:5432/spacey
      REDIS_URL: redis://redis:6379/0
      CORS_ORIGINS: http://localhost:5173,http://localhost:5174
      PROMETHEUS_ENABLED: "true"
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: ./server
    command: celery -A app.celery_app.celery_app worker -l info -Q ingest
    environment:
      DATABASE_URL: postgresql+asyncpg://spacey:spacey@db:5432/spacey
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  pgdata:


